id: opecha:P008004
initial_creation_type: ocr
source_metadata:
  id: bdr:W25102
  title: རིགས་ཀུན་འདུས་པའི་བདག་ཉིད་འཁོར་ལོའི་མགོན་པོ་མདོ་ཁམས་བརྒྱད་པ་རིན་པོ་ཆེ་དཔལ་ལྡན་ངག་དབང་མི་ཕམ་་་་་སྐལ་བཟང་དོན་བརྒྱུད་ཉི་མ་དགེ་ལེགས་ཕྲིན་ལས་ཀུན་ཁྱབ་ཕྱོགས་ལས་རྣམ་པར་རྒྱལ་བའི་སྡེའི་རྣམ་པར་ཐར་པའི་རིམ་པ་མདོ་ཙམ་བརྗོད་པ་ཨུཏ་པ
  volume:
    0331987492774ea8ab9629c7948204cc:
      image_group_id: I3861
      title: ''
      volume_number: 1
      total_pages: 506
    89dc0a5e99d84402aa52aca61efcd4e9:
      image_group_id: I3862
      title: ''
      volume_number: 2
      total_pages: 474
  author: ''
ebook_metadata:
  title: རིགས་ཀུན་འདུས་པའི་བདག་ཉིད་འཁོར་ལོའི་མགོན་པོ་མདོ་ཁམས་བརྒྱད་པ་རིན་པོ་ཆེ་དཔལ་ལྡན་ངག་དབང་མི་ཕམ་་་་་སྐལ་བཟང་དོན་བརྒྱུད་ཉི་མ་དགེ་ལེགས་ཕྲིན་ལས་ཀུན་ཁྱབ་ཕྱོགས་ལས་རྣམ་པར་རྒྱལ་བའི་སྡེའི་རྣམ་པར་ཐར་པའི་རིམ་པ་མདོ་ཙམ་བརྗོད་པ་ཨུཏ་པ
  author: ''
  sku: P008004
  cover: cover.jpg
  layers:
  - pagination
