id: opecha:P008004
initial_creation_type: ocr
source_metadata:
  id: bdr:W25102
  title: རིགས་ཀུན་འདུས་པའི་བདག་ཉིད་འཁོར་ལོའི་མགོན་པོ་མདོ་ཁམས་བརྒྱད་པ་རིན་པོ་ཆེ་དཔལ་ལྡན་ངག་དབང་མི་ཕམ་་་་་སྐལ་བཟང་དོན་བརྒྱུད་ཉི་མ་དགེ་ལེགས་ཕྲིན་ལས་ཀུན་ཁྱབ་ཕྱོགས་ལས་རྣམ་པར་རྒྱལ་བའི་སྡེའི་རྣམ་པར་ཐར་པའི་རིམ་པ་མདོ་ཙམ་བརྗོད་པ་ཨུཏ་པ
  volume: ''
  author: ''
